<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comment', 'doctrine');

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $like_
 * @property integer $dislike
 * @property integer $article_id
 * @property string $author
 * @property timestamp $created_at
 * @property string $content
 * @property Article $Article
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method integer   getLike_()      Returns the current record's "like_" value
 * @method integer   getDislike()    Returns the current record's "dislike" value
 * @method integer   getArticleId()  Returns the current record's "article_id" value
 * @method string    getAuthor()     Returns the current record's "author" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method string    getContent()    Returns the current record's "content" value
 * @method Article   getArticle()    Returns the current record's "Article" value
 * @method Comment   setId()         Sets the current record's "id" value
 * @method Comment   setLike_()      Sets the current record's "like_" value
 * @method Comment   setDislike()    Sets the current record's "dislike" value
 * @method Comment   setArticleId()  Sets the current record's "article_id" value
 * @method Comment   setAuthor()     Sets the current record's "author" value
 * @method Comment   setCreatedAt()  Sets the current record's "created_at" value
 * @method Comment   setContent()    Sets the current record's "content" value
 * @method Comment   setArticle()    Sets the current record's "Article" value
 * 
 * @package    blog_admin_system
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('like_', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dislike', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}