<?php

/**
 * Article
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    blog_admin_system
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{
	//	public function save(Doctrine_Connection $conn = null){
	//		$this->created_at = date('Y-m-d H:i:s', time());
	//		//$this->like_ = 0;
	//		//$this->dislike = 0;
	//		return parent::save($conn);
	//	}
	public function setCreatedAt($created_at) {
		if(!$created_at || $created_at==''){
			$this->created_at = date('Y-m-d H:i:s', time());;
		}else{
			parent::save($created_at);
		}
	}
}